### ISSUE TITLE
about Flag

### ISSUE THREAD

**Issue by lo-th** [fabmax/physx-js-webidl#19]
I see problem, is not a bug just a recommandation 
on Module definition you can have multiple export of same name 

for example PhysX.eFORCE is 
Module['eFORCE'] = _emscripten_enum_PxForceModeEnum_eFORCE(); __ 0
but also 
Module['eFORCE'] = _emscripten_enum_PxArticulationCacheFlagEnum_eFORCE();  __ 8
Module['eFORCE'] = _emscripten_enum_PxArticulationDriveTypeEnum_eFORCE(); __ 0

so take care to always use full definition
 PhysX._emscripten_enum_PxForceModeEnum_eFORCE();
 istead of PhysX.eFORCE
 
 that true for many flag ( eX, eTWIST ... )

**Comment by fabmax** [comment]
Yes I know, unfortunately this is generated by emscripten. I opened an [issue](https://github.com/emscripten-core/emscripten/issues/13243) about that a while ago but it never got fixed.
