### ISSUE TITLE
Profile & Debug builds

### ISSUE THREAD

**Issue by lucas-jones** [fabmax/physx-js-webidl#2]
What's thoughts on also including Profile & Debug builds in the `dist` folder?

**Comment by fabmax** [comment]
I don't have any experience in debugging wasm code and always assumed there aren't any useful tools to do that. Therefore I didn't see the point in providing such builds.

However, apparently there are ways to do that so adding debug builds seems to be a good idea.

**Comment by lucas-jones** [comment]
If I remember correctly a WASM Debug/Profile build shows the C++ function name when running a CPU profiling via Chrome Profiler. 
Also PhysX debug builds include stuff for the PhysX VisualDebugger (Can use `websockify` to then use it via browser)

https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/VisualDebugger.html

**Comment by fabmax** [comment]
Alright, I added wasm binaries for debug and profile builds (in `dist-debug/` and `dist-profile` respectively).

However, I haven't yet added any web-idl bindings to Pvd stuff, as that requires a bit more work and I'm quite busy at the moment :/

**Comment by lucas-jones** [comment]
Ace. I'll try giving it a go & pull-request

**Comment by nidin** [comment]
@lucas-jones Hey, did you manage to send data to PVD from the browser?

**Comment by lucas-jones** [comment]
Yes. Just proxying the data via websockify.

Make sure you're using a profile build.

`websockify 8090 127.0.0.1:5425`

https://gist.github.com/lucas-jones/3b62e0ff621b27555be3d15782b59518

**Comment by nidin** [comment]
Thanks for the quick reply. I will give it a try 👍
