### ISSUE TITLE
help about ccd

### ISSUE THREAD

**Issue by lo-th** [fabmax/physx-js-webidl#23]
Hello me again :)

i need help to enable ccd collision 
ccd need custom scene filterShader with pairFlags |= PxPairFlag::eDETECT_CCD_CONTACT;

but i dont find a way to make custom filter shader 

let sceneDesc = new PhysX.PxSceneDesc( tolerances );
sceneDesc.set_filterShader(PhysX.PxTopLevelFunctions.prototype.DefaultFilterShader());

i see PhysX.PxTopLevelFunctions.prototype.setupPassThroughFilterShader but ? 

any idea

**Comment by fabmax** [comment]
The default filter shader takes additional flags from `word2` of the actor's simulation filter data (see [here](https://github.com/fabmax/PhysX/blob/474277eeee2beec1349dc451dbfee0c2b6fe41dd/physx/source/webidlbindings/src/common/WebIdlBindings.h#L192)).

So all you need to do to enable CCD is to set the ENABLE_CCD flags in your `PxSceneDesc` and `PxRigidBody.setRigidBodyFlag()` and then something like `actor.simulationFilterData.word2 = _emscripten_enum_PxPairFlagEnum_eDETECT_CCD_CONTACT()`

**Comment by lo-th** [comment]
mm i try with word2 ; SOLVE_CONTACT | DETECT_DISCRETE_CONTACT | DETECT_CCD_CONTACT
but seem's don't work ?

**Comment by fabmax** [comment]
It should work (I use it that way). Did you also enable `PxSceneFlag.eENABLE_CCD` in your scene and `PxRigidBodyFlag.eENABLE_CCD` on your bodies?

**Comment by lo-th** [comment]
ok i find thank's for help 
i use the body flag on scene :)
now that work perfect
