### ISSUE TITLE
Packman Repo is Down

### ISSUE THREAD

**Issue by zalo** [fabmax/physx-js-webidl#26]
@fabmax New Builds are failing because Packman can't seem to find the build dependencies anymore:
https://github.com/zalo/physx-js-webidl/actions/runs/7217215226/job/19664671021#step:5:30

Is there a way to change where packman is pointing?

**Comment by zalo** [comment]
Ah, this is a problem with the base PhysX Repo:
https://github.com/NVIDIA-Omniverse/PhysX/issues/231
It's likely this repo will need to update to 5.3.1 just to be able to build after this 😅

Alternatively, if you have a copy of the old packman build folder, we can host that separately to let packman do its thing:
https://github.com/fabmax/PhysX/blob/webidl-bindings/physx/buildtools/packman/config.packman.xml#L3C73-L3C86

**Comment by fabmax** [comment]
The easiest option is probably to update to 5.3.1. The minor updates are usually relatively simple to do.

**Comment by zalo** [comment]
> The easiest option is probably to update to 5.3.1. The minor updates are usually relatively simple to do.

Actually, it seems like the answer might be simpler 🫠
https://github.com/NVIDIA-Omniverse/PhysX/discussions/230#discussion-5952884

Perhaps the Docker images can apply this as a patch until the update goes in 🤔

**Comment by fabmax** [comment]
I [added](https://github.com/fabmax/physx-js-webidl/commit/213e0cacb5c00f1fbe05e5bb2a38694d4d96a5a6) the packman update command to the `generate.sh` seems to fix the issue :+1:

**Comment by zalo** [comment]
Thank you so much for your speedy response!
