### ISSUE TITLE
[Question] Contact Callback Alternative?

### ISSUE THREAD

**Issue by regnaio** [fabmax/physx-js-webidl#36]
Currently, we can get contacts like:

```ts
const callback = new PhysX.PxSimulationEventCallbackImpl();
callback.onContact = (pairHeader: number, pairs: number, nbPairs: number): void => {
	// ...
}
```

However, callbacks seem like a roundabout way to get a list of contacts (and `eNOTIFY_TOUCH_PERSISTS` causes a large hit to performance). Instead, is there simply a list of contacts (Persistent Contact Manifold) we can just iterate through after simulating a step?

```ts
scene.simulate(timeStep);
scene.fetchResults(true);

// Iterate through contacts in Persistent Contact Manifold
```

Thank you for your help! 😄 

---

Please see an [example of how iterating through a Persistent Contact Manifold's contacts can be done in Bullet Physics](https://andysomogyi.github.io/mechanica/bullet.html), (which offers both an iterable list of contacts or a callback-based approach):

```c
//Assume world->stepSimulation or world->performDiscreteCollisionDetection has been called

int numManifolds = world->getDispatcher()->getNumManifolds();
for (int i = 0; i < numManifolds; i++)
{
    btPersistentManifold* contactManifold =  world->getDispatcher()->getManifoldByIndexInternal(i);
    const btCollisionObject* obA = contactManifold->getBody0();
    const btCollisionObject* obB = contactManifold->getBody1();

    int numContacts = contactManifold->getNumContacts();
    for (int j = 0; j < numContacts; j++)
    {
        btManifoldPoint& pt = contactManifold->getContactPoint(j);
        if (pt.getDistance() < 0.f)
        {
            const btVector3& ptA = pt.getPositionWorldOnA();
            const btVector3& ptB = pt.getPositionWorldOnB();
            const btVector3& normalOnB = pt.m_normalWorldOnB;
        }
    }
}
```

**Comment by fabmax** [comment]
Hmm, in PhysX I'm not aware of any other method than the callback approach. There's a section about extracting contact information in the [PhysX docs](https://nvidia-omniverse.github.io/PhysX/physx/5.4.1/docs/AdvancedCollisionDetection.html#extracting-contact-information), but they also only mention the simulation callback `onContact` function so I don't think there is another way.
