### ISSUE TITLE
Serialization/Deserialization Binary or XML

### ISSUE THREAD

**Issue by im-esteban** [fabmax/physx-js-webidl#39]
Hey, **fabmax**, it's been a while, i hope you are doing well!

I have been enjoying this project of yours so much. it's been almost a year and i see you have been up to it since then, thank you for giving so much to the community, i hope one day to give you back.

So i have been building a game all along and i'm at the point where i need to save the game and also where Serialization and Deserialization could become handy, so this is what i have come up with.

I'm not sure what RealPtr is, but there is a helper function that turn a VoidPtr into a RealPtr.
It has yielded me some values, i'm not sure if it is memory i'm supposed to access. 

Again, it would be very valuable if you could provide some insight into how this could be achieved using your library.
In the meanwhile a workaround would be to loop through every entity and grab every possible property to try to recreate the scene.

Take care **fabmax** and have a good day. 

``` javascript
    // Encoding - Player saves the game
    let registry = PhysX.PxSerialization.prototype.createSerializationRegistry(physics);
    let collection = PhysX.PxCollectionExt.prototype.createCollection(scene);
    let output = new PhysX.PxDefaultMemoryOutputStream();

    collection.add(rigidBody);

    PhysX.PxSerialization.prototype.complete(collection, registry);
    PhysX.PxSerialization.prototype.serializeCollectionToBinary(output, collection, registry);

    let voidPtr = output.getData();
    let realPtr = PhysX.NativeArrayHelpers.prototype.voidToRealPtr(voidPtr);
    let size = voidPtr.getSize();
    let base64 = "";

    for (let i = 0; i < size; i++) {

        let x = PhysX.NativeArrayHelpers.prototype.getRealAt(realPtr, i)

        if (i == 0) {
            base64 += btoa(x)
        }
        else {
            base64 += "-" + btoa(x)
        }
    }

    // Decoding - Player loads the save file
    let arrayBase64 = base64.split("-");
    let reconstructedRealPtr = new PhysX.PxRealPtr() // ERROR: No Constructor

    // am i doing it right?

    [...]

    PhysX.PxSerialization.prototype.createCollectionFromBinary(reconstructedRealPtr, collection, registry);
```

**Comment by fabmax** [comment]
A `real` is the PhysX version of a float and the `voidToRealPtr()` function casts the given raw pointer to a real / float pointer. That is probably not the best choice to read the data. Also your `voidPtr.getSize();` probably won't return the value you are expecting. The void pointer is really just an address in the WASM memory without any further information about the length of the values it is pointing to. The correct function should be `output.getSize()` (actually I don't know what value `voidPtr.getSize();` returns...)

A better option is to use u8 (i.e. bytes). It should work somewhat like this:

```js
const dataPtr = PhysX.NativeArrayHelpers.prototype.voidToU8Ptr(output.getData())
const data = new Uint8Array(PhysX.HEAPU8.buffer, dataPtr, output.getSize())
```

And then restore it like this:
```js
const buf = PhysX._malloc(data.length)
PhysX.HEAPU8.set(data, buf)
PhysX.PxSerialization.prototype.createCollectionFromBinary(buf, collection, registry)
PhysX._webidl_free(buf)
```

I haven't tested this and messing around with raw memory pointers is always a bit finicky, so now warranty 😃

**Comment by im-esteban** [comment]
Hey, thank you as always, i already settled on the workaround i just commented, but hey! it's good to see you again, i hope someone finds this useful. :)
