### ISSUE TITLE
how to get contactPair.shape[1] in simulationEventCallbackImpl.onContact?

### ISSUE THREAD

**Issue by Wxwind** [fabmax/physx-js-webidl#41]
```javascript
simulationEventCallbackImpl.onContact = (pairHeaderPointer, pairsPointer, nbPairs) => {
      const px = this._px;
      console.log(`onContact nbPairs:${nbPairs}`);

      const nativeArrayHelper = this._px.NativeArrayHelpers.prototype;
      for (let i = 0; i < nbPairs; i++) {
        const pair = nativeArrayHelper.getContactPairAt(pairsPointer, i);
        // pair.shape is defined as "PxShape* shapes[]" in source code but get likely "the pointer of pair.shapes[0]" here.
        console.log('contact pair.shapes', pair.shapes);
        const event = pair.events;

        // correct shape0
        const nativeShape0 = nativeArrayHelper.getShapeAt(pair.shapes as any, 0) as any;
        // always equals nativeShape0's ptr + 16
        const nativeShape1 = nativeArrayHelper.getShapeAt(pair.shapes as any, 1) as any;

        // if pair.shapes is PxShape**, it will works here, but pair.shapes looks like "PxShape*"
        const s0 = nativeArrayHelper.getU32At(pair.shapes as any, 0);
        const s1 = nativeArrayHelper.getU32At(pair.shapes as any, 1);
        const aaa = (this._px as any).wrapPointer(s0, this._px.PxShape) as PhysX.PxShape;
        const bbb = (this._px as any).wrapPointer(s1, this._px.PxShape) as PhysX.PxShape;
        console.log(aaa, bbb, nativeShape0, nativeShape1);
      }
    };
```

[Physx.ContactPair.shapes](https://github.com/fabmax/PhysX/blob/83d24766bd31d00779fcaaabe080d00ff5869ccd/physx/include/PxSimulationEventCallback.h#L531)  is PxShape**,  but the pair.shapes in simulationEventCallbackImpl.onContact is likely the pointer of px.shape[0]. It confused me a lot.
 1. When SimpleSimulationEventCallback is used? It's seems only defined on PhysxJniGlue.h and has no reference.
 2. How to get two shapes which particular in collision in OnContact?

**Comment by fabmax** [comment]
You need to register your `simulationEventCallback` on scene creation with `sceneDesc.set_simulationEventCallback(simulationEventCallback)`.

You can get the colliding actors via the pair header. I'm this [here](https://github.com/kool-engine/kool/blob/a9f4d874369301f9c0235b99926e2f047d063d08/kool-physics/src/jsMain/kotlin/de/fabmax/kool/physics/PhysicsWorld.js.kt#L236)
It's written in kotlin but uses the js lib under the hood, so it should translate to native js fairly well.

**Comment by Wxwind** [comment]
> You need to register your `simulationEventCallback` on scene creation with `sceneDesc.set_simulationEventCallback(simulationEventCallback)`.
> 
> You can get the colliding actors via the pair header. I'm doing this [here](https://github.com/kool-engine/kool/blob/a9f4d874369301f9c0235b99926e2f047d063d08/kool-physics/src/jsMain/kotlin/de/fabmax/kool/physics/PhysicsWorld.js.kt#L236)
> It's written in kotlin but uses the js lib under the hood, so it should translate to native js fairly well.

But I need to know which two shapes  collided, not only two rigidActors.

**Comment by Wxwind** [comment]
![image](https://github.com/user-attachments/assets/44a72016-001f-4fe2-b593-9a855c427c10)
I figure out that the shapes in contactPair definitely the shapes[0] shows in phys-js-webidl.js.
_emscripten_bind_PxContactPair_get_shapes_2 and _emscripten_bind_PxContactPair_set_shapes_1 are missing in phys-js-webidl.js.

**Comment by Wxwind** [comment]
demo's here
[test.zip](https://github.com/user-attachments/files/18235529/test.zip)

**Comment by Wxwind** [comment]
Finally I figuare out. pair.shapes means pari.get_shapes(undefined). Should never use pair.shapes. Instead, use pair.get_shapes and pair.set_shapes
![image](https://github.com/user-attachments/assets/f58cdd73-331c-49cd-b8bf-4f615c3c93d1)

get_shapes and set_shapes in c++ (glue.cpp) like this:
![image](https://github.com/user-attachments/assets/9727eaee-f346-4ac0-91b8-ada26787d983)
